### ISSUE TITLE
Bug: Path is not url safe

### ISSUE THREAD

**Issue by hmycroft** [michaelliao/githubpy#13]
Hello,

I've been playing around with your nice interface to github and I ran into a problem with a url that contains a space. Your path is not url encoded (e.g " " -> "%20").

You can reproduce the bug with "githubpy.GitHub().repos("stevedekorte\io\addons\AVCodec\source\old\IoAVCodec copy.c").get()". I have no idea what that is, I was just playing around with github and githubpy to figure things out! :)

I've changed the line in _Executable::__init__ from
   self._path = path
to
   self._path = urllib.quote(path)

And now it seems to work!

Thanks!

**Comment by ninjatrench** [comment]
if it worked then fork, update and make a pull request. so everyone can get around with this bug.

**Comment by michaelliao** [comment]
fixed
