### ISSUE TITLE
Issues include pull requests

### ISSUE THREAD

**Issue by jhuus** [michaelliao/githubpy#21]
I see that gh.repos()().issues.get(filter='all', state='all') is returning a mix of issues and pull requests. How do I get it to return only issues?

**Comment by twidi** [comment]
I think you can't.

As stated here https://developer.github.com/v3/issues/#list-issues, `every pull request is an issue`.
You can easily filter after that to exclude pull requests by looking at the `pull_request` key (willb e not set, or empty, for normal issues)

**Comment by jhuus** [comment]
Got it. Thanks!
