### ISSUE TITLE
Commits count not coming

### ISSUE THREAD

**Issue by ukreddy-erwin** [michaelliao/githubpy#35]
With the curl command:

curl -I --user "username:password" https://api.github.com/repos/<account>/<repo>/commits?per_page=1

will give a json output where at the "List=" section we will get number of commits in the repo for master branch.For other branch, we will add &sha='branch' at the end.

How to frame this in your python code?

**Comment by michaelliao** [comment]
https://docs.github.com/en/rest/commits/commits?apiVersion=2022-11-28#list-commits

```
>>> gh.repos('michaelliao')('githubpy').commits.get(sha='master', per_page=10)
[{'sha': '232203c9eda4fd1f3905bc2e45df5c7a802ba2df', 'node_id': ...
```
