### ISSUE TITLE
Deleting a file from repository fails with 422 ERROR.

### ISSUE THREAD

**Issue by karthikdialpad** [michaelliao/githubpy#58]
I am trying to use the githubpy library in my setup. My requirement is to delete a file from the repo.
My code looks like below
```
github_client = github.GitHub(access_token=access_token)
content = github_client.repos(owner)(repo)('contents')(file_name).get(ref=branch)
github_client.repos(owner)(repo)('contents')(file_name).delete(message=message, sha=content.get('sha'), branch=branch))
```
The expected result is the file should be deleted, but I get an error 422 Unprocessable entity.
When looking further into it. I see that I get an ApiError with below message
```
{'request': {'method': 'DELETE', 'url': 'url_of_the_file'}, 'response': {'code': 422, 'json': {'message': 'Invalid request.\n\n"message", "sha" weren\'t supplied.', 'documentation_url': 'https://docs.github.com/rest/reference/repos#delete-a-file'}}}
``` 

The error message says sha weren't supplied, but I am passing the blob sha of the file properly.
When I run the equivalent curl command it works fine.
```
curl -L \
  -X DELETE \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>"\
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/OWNER/REPO/contents/PATH \
  -d '{"message":"my commit message","committer":{"name":"Monalisa Octocat","email":"octocat@github.com"},"sha":"329688480d39049927147c162b9d2deaf885005f"}'
```

Can I know whether the githubpy support the delete operation of a file?

**Comment by michaelliao** [comment]
delete is supported. please check the test code:

https://github.com/michaelliao/githubpy/blob/7eb713acb7c050761561920b2c76bfd1457e6791/sample_content.py#L69

**Comment by michaelliao** [comment]
use

```
delete(
    {
        'message': 'message',
        'sha': '0x'
    }
)
```

**Comment by karthikdialpad** [comment]
Hi @michaelliao,
Thanks for your response.
I see from the code that the delete operation is supported [recently](https://github.com/michaelliao/githubpy/commit/573d1079520561b7b060a11da66c5b781d8a60a4).
I don't see any release that happened post that, so whenever I download the library using `pip install githubpy` I get the 1.1.0 version of the module that doesn't have the latest changes that I am looking for. 
May I know when are you planning to release the latest changes?

**Comment by michaelliao** [comment]
2.0.0 is published to pip.

https://pypi.org/project/githubpy/
